### PR TITLE
Updated to .Net Standard 2.0

### PR DESCRIPTION
**Pull request by Chris-ZA**
Updated library project to .Net Standard 2.0 and Test project to .Net Framework 4.7.
Fixed some small typos and updated nuget packages in the Test project.

I created new .Net Standard 2.0 project and copied the contents of old FluentConsole project into it. The original main FluentConsole project is still there but is now called FluentConsole.Net45 but it's not loaded in the solution file.  You can delete it of you're happy with the new library project.

I also added the nuget settings to the project properties with the same information as was in the AssemblyInfo.cs file and also added your post build step to build the nuget back.

Finally, I renamed the original .Net Framework demo project to FluentConsole.NetFramework.Demo and created another demo project for .Net Core called FluentConsole.NetCore.Demo.  Not great names, I know.  Feel free to amend as you wish.

Hope this helps.  You should be able to step the versions of .Net core and .Net Framework down as you require.

Let me know if you have any questions or need anything else done.

Regards,

Chris

### CODE REVIEW

**Comment by Chris-ZA** [comment]
Not sure how to resolve the AppVeyor build error.  Never used it before.  According to articles I've just read, the msbuild version must v15.  

See here:  https://stackoverflow.com/questions/42509313/the-default-xml-namespace-of-the-project-must-be-the-msbuild-xml-namespace/44166281#44166281

**Comment by Chris-ZA** [comment]
OK.  I created an AppVeyor account and got the build working by selecting Visual Studio 2017 as the build worker image and adding the following 2 pre-build commands:

dotnet restore
nuget restore

Now the issue is 2 tests are failing and I don't understand why.

https://ci.appveyor.com/project/Chris42131/fluentconsole/build/tests

Any ideas?

**Comment by refactorsaurusrex** [comment]
Hey Chris, sorry for the long delay. I will look at this as soon as I can. Might not happen until this weekend.

**Review by refactorsaurusrex — COMMENTED** [review]
Not sure I understand the reasoning behind the project renames?

**Comment by refactorsaurusrex** [comment]
> The original main FluentConsole project is still there but is now called FluentConsole.Net45 but it's not loaded in the solution file.

Why not just change the target framework and leave the original name intact?

**Comment by refactorsaurusrex** [comment]
Closing due to inactivity.

**Pull request closed without merging**
